<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### PHILIPM3

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```

```{r}
setwd("C:/Users/PHILIPM3/OneDrive - Cleveland Clinic/GitHub/biostats/CHAOSS")
```


```{r}
setwd("C:/Users/philipm3/OneDrive - Cleveland Clinic/Academics/_Biostatistics")
```


```{r}
setwd("C:/Users/PHILIPM3/OneDrive - Cleveland Clinic/GitHub/biostats/CHAOSS")
```


```{r}
CHAOSS <-
readXL("C:/Users/PHILIPM3/OneDrive - Cleveland Clinic/GitHub/biostats/CHAOSS/Handedness in Surgery Study data.xlsx",
rownames=FALSE, header=TRUE, na="", sheet="Sheet1", stringsAsFactors=TRUE)
```


```{r}
str(CHAOSS)
```


```{r}
Righthanders <- subset(CHAOSS, subset=Hand=="right")
```


```{r}
str(Righthanders)
```


```{r}
CHAOSS <- within(CHAOSS, {
Quick <- Recode(Time, '0:5="1"; 5.01:1000="0"; else="NA"', as.factor=TRUE,
to.value="=", interval=":", separator=";")
})
```


```{r}
str(CHAOSS)
```

